name: redis
services:
  redis-cache:
    image: redis:6.2-alpine
    networks:
      mariadb-network: null
      redis-network: null
    volumes:
      - type: volume
        source: redis-cache-data
        target: /data
        volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      mariadb-network: null
      redis-network: null
    volumes:
      - type: volume
        source: redis-queue-data
        target: /data
        volume: {}